name: upper-build

on:
  push:
    paths:
      - '.github/workflows/upper-build.yml'
      - 'upper/**'
  workflow_dispatch: # manual

jobs:
  build:
    runs-on: macos-latest
    steps:
      - run: pwd && ls -al # print out current directory and list files
      - uses: actions/checkout@v4
      - run: pwd && ls -al
      - run: go version
      - uses: actions/setup-go@v5
        with:
          # go-version: '1.22'
          go-version-file: './upper/go.mod'
          cache-dependendency-path: './upper/go.sum'
      - run: go mod download # will consolidate the step of downloading dependencies
        working-directory: upper
      - run: go version
      - run: |
          ls
          go build
          ls
          go test
          ./upper foo the bar
        working-directory: upper
        name: Build and Test
